# == Application ==========================================
spring.application.name=crm-backend

# == Database  =============================================
spring.datasource.url=jdbc:mysql://localhost:3306/crm_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# == JPA / Hibernate =======================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

## == Jackson ===============================================
#spring.jackson.serialization.write-dates-as-timestamps=false
#spring.jackson.default-property-inclusion=non_null

# == Server ================================================
server.port=8080

# == JWT ===================================================
#jwt.secret=your-256-bit-secret-key-change-this-in-production
#jwt.expiration=86400000
#jwt.refresh-expiration=604800000

# == Logging ===============================================

logging.level.com.crm=DEBUG
logging.level.org.springframework.security=DEBUG
